# Generated by Django 4.2.7 on 2024-02-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_user_type_remove_tutor_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tutor'),
        ),
    ]
