# Generated by Django 4.2.7 on 2023-12-18 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='liked_by_user',
            field=models.ManyToManyField(blank=True, related_name='session_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
