# Generated by Django 4.2.7 on 2024-01-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_interaction_liked_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('session_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_comment', to='interactions.interaction')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
