# Generated by Django 4.2.7 on 2024-02-27 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0007_chatroom_chatroommessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yogahub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%M/%D')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likecount', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
