# Generated by Django 4.2.7 on 2024-02-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_yogahub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogahub',
            name='slug',
        ),
    ]
