# Generated by Django 4.2.7 on 2023-12-16 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('classroom_equipment', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('class_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.classtype')),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to='users.profile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
