# Generated by Django 4.2.4 on 2023-12-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('schedule_time', models.DateTimeField()),
                ('classroom_equipment', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('class_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.classtype')),
                ('enrolled_students', models.ManyToManyField(related_name='enrolled_classes', to='users.profile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
