# Generated by Django 4.2.4 on 2023-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tutor'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to='users.profile'),
        ),
    ]
