# Generated by Django 4.2.7 on 2024-02-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_user_type_remove_tutor_user_profile_and_more'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tutor'),
        ),
    ]
