# Generated by Django 4.2.4 on 2023-12-09 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_yogaclass_enrolled_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
