# Generated by Django 4.2.7 on 2024-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_yogaclass_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='audio_material',
            field=models.FileField(blank=True, null=True, upload_to='audio_materials/'),
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='image_material',
            field=models.ImageField(blank=True, null=True, upload_to='image_materials/'),
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='pdf_material',
            field=models.FileField(blank=True, null=True, upload_to='pdf_materials/'),
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='video_material',
            field=models.FileField(blank=True, null=True, upload_to='video_materials/'),
        ),
    ]
