# Generated by Django 4.2.7 on 2024-02-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_yogaclass_audio_material_yogaclass_image_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='pdf_material',
        ),
    ]
