# Generated by Django 4.2.7 on 2023-12-16 13:18

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '__first__'),
        ('users', '0003_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('Video', 'Video'), ('Photo', 'Photo'), ('Text', 'Text'), ('Audio', 'Audio')], max_length=50)),
                ('content', models.TextField()),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('material_file', models.FileField(upload_to=materials.models.material_upload_path)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.yogaclass')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
