# Generated by Django 4.2.7 on 2024-02-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
